services:
  aqua-chroma:
    build: .
    ports:
      - '19997:3000'
    env_file:
      - .env.production
    networks:
      - shared_app_net
    restart: unless-stopped

networks:
  shared_app_net:
    external: true
    name: shared-db-network